In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

path = "../final_data/tracking_player.csv"
df = pd.read_csv(path)
df.head()

,game_id,period,time,wallclock,live,possession,player_id,player_name,loc_x,loc_y,loc_z,spd,dist,opta_id
0,2312135,1,0.0,1676118667880,False,home,0746befc-a701-4b33-8faf-b3cccccf17bb,25,-11.08,1.55,0.0,0.0,0.0,192194
1,2312135,1,0.0,1676118667880,False,home,08d71d20-85ad-4d98-8bc0-36b8e39e517a,9,-0.15,-30.50,0.0,0.0,0.0,174349
2,2312135,1,0.0,1676118667880,False,home,092fcb72-e828-4d76-b7b9-abdf8c0d07ad,12,11.04,-4.63,0.0,0.0,0.0,226718
3,2312135,1,0.0,1676118667880,False,home,16bae841-2083-41fa-a659-031ee07d867d,25,-0.16,9.02,0.0,0.0,0.0,191720
4,2312135,1,0.0,1676118667880,False,home,1ab5dc11-1e32-4e6b-a385-5b736ec14763,7,-2.71,8.54,0.0,0.0,0.0,96385

In [2]:
df['new_time'] = 0
df.loc[(df['period'] == 1), 'new_time'] = df['time'] 
df.loc[(df['period'] == 2), 'new_time'] = round(df['time'] + round(df[df['period'] == 1]["time"].tolist()[-1],2),2) # 2829.24
df["time"] = df['new_time']

In [3]:
# MCWF
player_home = pd.read_csv("../final_data/player.csv")
player_home = player_home[player_home["teamSsiId"] == "edfee15e-0dd7-42bc-be2a-289870187ddc"]
player_ids_home = player_home["ssiId"].tolist()
print(player_ids_home)

# a11d34f3-da66-4219-9332-85421e44692f
player_away = pd.read_csv("../final_data/player.csv")
player_away= player_away[player_away["teamSsiId"] == "a11d34f3-da66-4219-9332-85421e44692f"]
player_ids_away = player_away["ssiId"].tolist()
print(player_ids_away)

['047e1396-3bc4-4517-9fa6-e3ba53998329', '87dbfea7-b4c1-49ce-b210-6210f5efae55', 'c4cfb3c0-beff-41dd-82ba-98ec35dd6e1a', 'ecc2bc47-7756-4a17-8ba1-bfcf5e5d950d', '7379ed0c-d52a-46af-a1f6-b6312fc9bfc1', '48f9e1b7-366b-4ae0-972b-47f268603c3f', '08d71d20-85ad-4d98-8bc0-36b8e39e517a', '8c34093f-843c-41a4-b02d-1ed289de00a3', '3706abe8-9aba-49c6-8a8f-4f4ef2a9be70', 'a5ec6d76-4788-4894-bea2-0a165d4a36ba', 'eb23d9b0-cf56-4eb2-9a72-0022f70e3125', 'e49a0083-44e5-4399-8b69-845c4585617d', '724f3280-015e-440e-b9b7-0598833e9c2d', '0746befc-a701-4b33-8faf-b3cccccf17bb', 'db47bb9a-634f-4ef6-9cd0-d6daf74164d7', '1b3bd37a-8d98-4834-8d8f-072e2038e7c4', '1027258f-9b54-4cbf-b221-8ab62c169e08', '25cccc61-791d-4d74-8ef1-db3afa17a8e8', 'aa53177e-f36d-4298-9c67-3c93a49c3325', '471aedfa-df6f-44b4-b008-7b2cef31f3cb', '293704f8-5331-4d70-b691-c39a763f08f8', '1ab5dc11-1e32-4e6b-a385-5b736ec14763', '02780bab-8db4-4310-ad80-308ae2fa0a86', '27211092-da7c-4755-8e7a-ed1a5158628e', '2261b537-5d03-422a-94c5-7b1c33856088']
['d588cf67-0e75-4619-a541-d0945138b3fb', 'f3a6c7a6-4686-4c77-8e87-5bd842ec1642', '2b4f2f32-87cb-4cc7-bf6c-211f5ad1242a', '5551eb44-290b-426d-9311-8154e778d407', '8b2decb4-3722-4313-b0a0-d0a48e39aeb2', 'c7598a8f-b910-46a7-8ee3-c052c228ceff', '092fcb72-e828-4d76-b7b9-abdf8c0d07ad', '5ee28902-a961-4cbc-855e-84e4af865a70', 'e8b086da-181d-4404-9e80-bf4b0035e2ec', 'a63bc99a-6a68-4934-9a17-d4117c810085', '16bae841-2083-41fa-a659-031ee07d867d', '58ea1436-2616-4b0c-ab27-d1432ef8c2c9', '8346edc5-fb22-413e-8d8e-553c45349582', '487017fc-8cec-4889-8f4d-842edabd9f06', 'dc64b316-4b36-4467-838c-96bcbc242748', '8446653e-8da9-44b1-9b01-2cc7fd19481b', '717476ee-73a9-45d6-b95d-ddf4182ee262', '2c5def63-7238-4ca2-aa32-5ccbabe5a0b0', 'bea130d3-e02f-4d51-b301-2ef18a880a95', 'f7ae46be-3ace-423d-bee0-3482b314eb2e']

In [4]:
cols_lst_home = []
for i in player_ids_home:
    col_x = "Home_"+i+"_x"
    col_y = "Home_"+i+"_y"
    cols_lst_home.append(col_x)
    cols_lst_home.append(col_y)
cols_lst_away = []

for i in player_ids_away:
    col_x = "Away_"+i+"_x"
    col_y = "Away_"+i+"_y"
    cols_lst_away.append(col_x)
    cols_lst_away.append(col_y)

print(cols_lst_home)
print(cols_lst_away)

['Home_047e1396-3bc4-4517-9fa6-e3ba53998329_x', 'Home_047e1396-3bc4-4517-9fa6-e3ba53998329_y', 'Home_87dbfea7-b4c1-49ce-b210-6210f5efae55_x', 'Home_87dbfea7-b4c1-49ce-b210-6210f5efae55_y', 'Home_c4cfb3c0-beff-41dd-82ba-98ec35dd6e1a_x', 'Home_c4cfb3c0-beff-41dd-82ba-98ec35dd6e1a_y', 'Home_ecc2bc47-7756-4a17-8ba1-bfcf5e5d950d_x', 'Home_ecc2bc47-7756-4a17-8ba1-bfcf5e5d950d_y', 'Home_7379ed0c-d52a-46af-a1f6-b6312fc9bfc1_x', 'Home_7379ed0c-d52a-46af-a1f6-b6312fc9bfc1_y', 'Home_48f9e1b7-366b-4ae0-972b-47f268603c3f_x', 'Home_48f9e1b7-366b-4ae0-972b-47f268603c3f_y', 'Home_08d71d20-85ad-4d98-8bc0-36b8e39e517a_x', 'Home_08d71d20-85ad-4d98-8bc0-36b8e39e517a_y', 'Home_8c34093f-843c-41a4-b02d-1ed289de00a3_x', 'Home_8c34093f-843c-41a4-b02d-1ed289de00a3_y', 'Home_3706abe8-9aba-49c6-8a8f-4f4ef2a9be70_x', 'Home_3706abe8-9aba-49c6-8a8f-4f4ef2a9be70_y', 'Home_a5ec6d76-4788-4894-bea2-0a165d4a36ba_x', 'Home_a5ec6d76-4788-4894-bea2-0a165d4a36ba_y', 'Home_eb23d9b0-cf56-4eb2-9a72-0022f70e3125_x', 'Home_eb23d9b0-cf56-4eb2-9a72-0022f70e3125_y', 'Home_e49a0083-44e5-4399-8b69-845c4585617d_x', 'Home_e49a0083-44e5-4399-8b69-845c4585617d_y', 'Home_724f3280-015e-440e-b9b7-0598833e9c2d_x', 'Home_724f3280-015e-440e-b9b7-0598833e9c2d_y', 'Home_0746befc-a701-4b33-8faf-b3cccccf17bb_x', 'Home_0746befc-a701-4b33-8faf-b3cccccf17bb_y', 'Home_db47bb9a-634f-4ef6-9cd0-d6daf74164d7_x', 'Home_db47bb9a-634f-4ef6-9cd0-d6daf74164d7_y', 'Home_1b3bd37a-8d98-4834-8d8f-072e2038e7c4_x', 'Home_1b3bd37a-8d98-4834-8d8f-072e2038e7c4_y', 'Home_1027258f-9b54-4cbf-b221-8ab62c169e08_x', 'Home_1027258f-9b54-4cbf-b221-8ab62c169e08_y', 'Home_25cccc61-791d-4d74-8ef1-db3afa17a8e8_x', 'Home_25cccc61-791d-4d74-8ef1-db3afa17a8e8_y', 'Home_aa53177e-f36d-4298-9c67-3c93a49c3325_x', 'Home_aa53177e-f36d-4298-9c67-3c93a49c3325_y', 'Home_471aedfa-df6f-44b4-b008-7b2cef31f3cb_x', 'Home_471aedfa-df6f-44b4-b008-7b2cef31f3cb_y', 'Home_293704f8-5331-4d70-b691-c39a763f08f8_x', 'Home_293704f8-5331-4d70-b691-c39a763f08f8_y', 'Home_1ab5dc11-1e32-4e6b-a385-5b736ec14763_x', 'Home_1ab5dc11-1e32-4e6b-a385-5b736ec14763_y', 'Home_02780bab-8db4-4310-ad80-308ae2fa0a86_x', 'Home_02780bab-8db4-4310-ad80-308ae2fa0a86_y', 'Home_27211092-da7c-4755-8e7a-ed1a5158628e_x', 'Home_27211092-da7c-4755-8e7a-ed1a5158628e_y', 'Home_2261b537-5d03-422a-94c5-7b1c33856088_x', 'Home_2261b537-5d03-422a-94c5-7b1c33856088_y']
['Away_d588cf67-0e75-4619-a541-d0945138b3fb_x', 'Away_d588cf67-0e75-4619-a541-d0945138b3fb_y', 'Away_f3a6c7a6-4686-4c77-8e87-5bd842ec1642_x', 'Away_f3a6c7a6-4686-4c77-8e87-5bd842ec1642_y', 'Away_2b4f2f32-87cb-4cc7-bf6c-211f5ad1242a_x', 'Away_2b4f2f32-87cb-4cc7-bf6c-211f5ad1242a_y', 'Away_5551eb44-290b-426d-9311-8154e778d407_x', 'Away_5551eb44-290b-426d-9311-8154e778d407_y', 'Away_8b2decb4-3722-4313-b0a0-d0a48e39aeb2_x', 'Away_8b2decb4-3722-4313-b0a0-d0a48e39aeb2_y', 'Away_c7598a8f-b910-46a7-8ee3-c052c228ceff_x', 'Away_c7598a8f-b910-46a7-8ee3-c052c228ceff_y', 'Away_092fcb72-e828-4d76-b7b9-abdf8c0d07ad_x', 'Away_092fcb72-e828-4d76-b7b9-abdf8c0d07ad_y', 'Away_5ee28902-a961-4cbc-855e-84e4af865a70_x', 'Away_5ee28902-a961-4cbc-855e-84e4af865a70_y', 'Away_e8b086da-181d-4404-9e80-bf4b0035e2ec_x', 'Away_e8b086da-181d-4404-9e80-bf4b0035e2ec_y', 'Away_a63bc99a-6a68-4934-9a17-d4117c810085_x', 'Away_a63bc99a-6a68-4934-9a17-d4117c810085_y', 'Away_16bae841-2083-41fa-a659-031ee07d867d_x', 'Away_16bae841-2083-41fa-a659-031ee07d867d_y', 'Away_58ea1436-2616-4b0c-ab27-d1432ef8c2c9_x', 'Away_58ea1436-2616-4b0c-ab27-d1432ef8c2c9_y', 'Away_8346edc5-fb22-413e-8d8e-553c45349582_x', 'Away_8346edc5-fb22-413e-8d8e-553c45349582_y', 'Away_487017fc-8cec-4889-8f4d-842edabd9f06_x', 'Away_487017fc-8cec-4889-8f4d-842edabd9f06_y', 'Away_dc64b316-4b36-4467-838c-96bcbc242748_x', 'Away_dc64b316-4b36-4467-838c-96bcbc242748_y', 'Away_8446653e-8da9-44b1-9b01-2cc7fd19481b_x', 'Away_8446653e-8da9-44b1-9b01-2cc7fd19481b_y', 'Away_717476ee-73a9-45d6-b95d-ddf4182ee262_x', 'Away_717476ee-73a9-45d6-b95d-ddf4182ee262_y', 'Away_2c5def63-7238-4ca2-aa32-5ccbabe5a0b0_x', 'Away_2c5def63-7238-4ca2-aa32-5ccbabe5a0b0_y', 'Away_bea130d3-e02f-4d51-b301-2ef18a880a95_x', 'Away_bea130d3-e02f-4d51-b301-2ef18a880a95_y', 'Away_f7ae46be-3ace-423d-bee0-3482b314eb2e_x', 'Away_f7ae46be-3ace-423d-bee0-3482b314eb2e_y']

In [5]:
final = pd.DataFrame(columns=['Frame', 'Period', 'Time [s]'] + cols_lst_home) 
final["Time [s]"] = np.round(np.arange(0, 6600, 0.04),2)#df.time.unique()
final["Period"].iloc[0:76667] =1
final["Period"].iloc[76668:] =2
final

# final["Time [s]"] = df.time.unique()
# final["Period"] = df.period
# final.Period.unique()

,Frame,Period,Time [s],Home_047e1396-3bc4-4517-9fa6-e3ba53998329_x,Home_047e1396-3bc4-4517-9fa6-e3ba53998329_y,Home_87dbfea7-b4c1-49ce-b210-6210f5efae55_x,Home_87dbfea7-b4c1-49ce-b210-6210f5efae55_y,Home_c4cfb3c0-beff-41dd-82ba-98ec35dd6e1a_x,Home_c4cfb3c0-beff-41dd-82ba-98ec35dd6e1a_y,Home_ecc2bc47-7756-4a17-8ba1-bfcf5e5d950d_x,...,Home_293704f8-5331-4d70-b691-c39a763f08f8_x,Home_293704f8-5331-4d70-b691-c39a763f08f8_y,Home_1ab5dc11-1e32-4e6b-a385-5b736ec14763_x,Home_1ab5dc11-1e32-4e6b-a385-5b736ec14763_y,Home_02780bab-8db4-4310-ad80-308ae2fa0a86_x,Home_02780bab-8db4-4310-ad80-308ae2fa0a86_y,Home_27211092-da7c-4755-8e7a-ed1a5158628e_x,Home_27211092-da7c-4755-8e7a-ed1a5158628e_y,Home_2261b537-5d03-422a-94c5-7b1c33856088_x,Home_2261b537-5d03-422a-94c5-7b1c33856088_y
0,NaN,1,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1,0.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,1,0.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,1,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,1,0.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164995,NaN,2,6599.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164996,NaN,2,6599.84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164997,NaN,2,6599.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164998,NaN,2,6599.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164999,NaN,2,6599.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# game_id = 2312135
# count = 0 
# for i in player_ids_home:
#     print(i)
#     col_x = "Home_"+i+"_x"
#     col_y = "Home_"+i+"_y"
#     p_df = df[(df["game_id"] == game_id) & (df["player_id"] == i) ]
#     p_df = df[(df["game_id"] == game_id) & (df["player_id"] ==i) ]
#     p_df = p_df[['period', 'time','player_id','loc_x','loc_y']]

#     # rename the columns in df2
#     final = final.rename(columns={
#         'Time [s]': 'time',
#         col_x: 'loc_x',
#         col_y: 'loc_y'
#     })


#     # perform the inner join
#     if(count == 0):
#         final = final.rename(columns={
#         'Time [s]': 'time',
#         col_x: 'loc_x',
#         col_y: 'loc_y'
#         })
#         merged_df = pd.merge(final,p_df , on='time', how='left')
#     else:
#         merged_df = merged_df.rename(columns={
#         col_x: 'loc_x',
#         col_y: 'loc_y'
#         })
#         merged_df = pd.merge(merged_df,p_df , on='time', how='left')

#     # select the desired columns and assign them to the new names
#     merged_df[col_x] = merged_df['loc_x_x'].fillna(merged_df['loc_x_y'])
#     merged_df[col_y] = merged_df['loc_y_x'].fillna(merged_df['loc_y_y'])
#     merged_df
#     # # drop the now-redundant columns
#     merged_df = merged_df.drop(columns=['loc_x_x', 'loc_y_x', 'loc_x_y', 'loc_y_y', 'period', 'player_id'])
#     final = final.drop(columns=['loc_x', 'loc_y'])
#     count +=1
#     # print(merged_df)

In [7]:
len(player_ids_home)

25

In [8]:
# tt = 6

for tt in range(0,len(player_ids_home)):
    game_id = 2312135
    count = tt
    i = player_ids_home[tt]
    print(i)
    col_x = "Home_"+i+"_x"
    col_y = "Home_"+i+"_y"
    p_df = df[(df["game_id"] == game_id) & (df["player_id"] == i) ]
    p_df = df[(df["game_id"] == game_id) & (df["player_id"] ==i) ]
    p_df = p_df[['period', 'time','loc_x','loc_y']]
    if( len(p_df) == 0 ):
        continue
    p_df = p_df.rename(columns={
        'time': 'Time [s]',
        'loc_x' : col_x ,
        'loc_y': col_y
    })
    print('here')
    p_df = p_df.drop_duplicates(subset=["Time [s]"])

    final = final.merge(p_df, how='left', left_on=["Time [s]"], right_on=["Time [s]"])
    final[col_x] = final[col_x +'_y'].fillna(final[col_x+'_x'])
    final = final.drop([col_x+'_x', col_x+'_y'], axis=1)
    final[col_y] = final[col_y +'_y'].fillna(final[col_y+'_x'])
    final = final.drop([col_y+'_x', col_y+'_y'], axis=1)

047e1396-3bc4-4517-9fa6-e3ba53998329
87dbfea7-b4c1-49ce-b210-6210f5efae55
here
c4cfb3c0-beff-41dd-82ba-98ec35dd6e1a
ecc2bc47-7756-4a17-8ba1-bfcf5e5d950d
7379ed0c-d52a-46af-a1f6-b6312fc9bfc1
48f9e1b7-366b-4ae0-972b-47f268603c3f
08d71d20-85ad-4d98-8bc0-36b8e39e517a
here
8c34093f-843c-41a4-b02d-1ed289de00a3
here
3706abe8-9aba-49c6-8a8f-4f4ef2a9be70
here
a5ec6d76-4788-4894-bea2-0a165d4a36ba
here
eb23d9b0-cf56-4eb2-9a72-0022f70e3125
here
e49a0083-44e5-4399-8b69-845c4585617d
724f3280-015e-440e-b9b7-0598833e9c2d
here
0746befc-a701-4b33-8faf-b3cccccf17bb
here
db47bb9a-634f-4ef6-9cd0-d6daf74164d7
here
1b3bd37a-8d98-4834-8d8f-072e2038e7c4
1027258f-9b54-4cbf-b221-8ab62c169e08
25cccc61-791d-4d74-8ef1-db3afa17a8e8
aa53177e-f36d-4298-9c67-3c93a49c3325
here
471aedfa-df6f-44b4-b008-7b2cef31f3cb
here
293704f8-5331-4d70-b691-c39a763f08f8
1ab5dc11-1e32-4e6b-a385-5b736ec14763
here
02780bab-8db4-4310-ad80-308ae2fa0a86
27211092-da7c-4755-8e7a-ed1a5158628e
2261b537-5d03-422a-94c5-7b1c33856088

In [9]:
final = final[final.columns.drop(list(final.filter(regex='period')))]
final

,Frame,Period,Time [s],Home_047e1396-3bc4-4517-9fa6-e3ba53998329_x,Home_047e1396-3bc4-4517-9fa6-e3ba53998329_y,Home_c4cfb3c0-beff-41dd-82ba-98ec35dd6e1a_x,Home_c4cfb3c0-beff-41dd-82ba-98ec35dd6e1a_y,Home_ecc2bc47-7756-4a17-8ba1-bfcf5e5d950d_x,Home_ecc2bc47-7756-4a17-8ba1-bfcf5e5d950d_y,Home_7379ed0c-d52a-46af-a1f6-b6312fc9bfc1_x,...,Home_0746befc-a701-4b33-8faf-b3cccccf17bb_x,Home_0746befc-a701-4b33-8faf-b3cccccf17bb_y,Home_db47bb9a-634f-4ef6-9cd0-d6daf74164d7_x,Home_db47bb9a-634f-4ef6-9cd0-d6daf74164d7_y,Home_aa53177e-f36d-4298-9c67-3c93a49c3325_x,Home_aa53177e-f36d-4298-9c67-3c93a49c3325_y,Home_471aedfa-df6f-44b4-b008-7b2cef31f3cb_x,Home_471aedfa-df6f-44b4-b008-7b2cef31f3cb_y,Home_1ab5dc11-1e32-4e6b-a385-5b736ec14763_x,Home_1ab5dc11-1e32-4e6b-a385-5b736ec14763_y
0,NaN,1,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-11.08,1.55,-0.12,24.02,-21.61,-8.56,-1.20,-13.96,-2.71,8.54
1,NaN,1,0.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-11.08,1.57,-0.12,24.01,-21.60,-8.56,-1.22,-13.95,-2.71,8.52
2,NaN,1,0.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-11.07,1.59,-0.12,24.01,-21.58,-8.56,-1.24,-13.93,-2.71,8.50
3,NaN,1,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-11.07,1.61,-0.12,24.00,-21.57,-8.56,-1.27,-13.92,-2.72,8.48
4,NaN,1,0.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-11.05,1.63,-0.11,24.00,-21.56,-8.56,-1.29,-13.90,-2.72,8.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164995,NaN,2,6599.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164996,NaN,2,6599.84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164997,NaN,2,6599.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164998,NaN,2,6599.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164999,NaN,2,6599.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
final.to_csv("final_home.csv")

In [ ]:
game_id = 2312135
tt = 1
count = tt
i = player_ids_home[tt]
print(i)
col_x = "Home_"+i+"_x"
col_y = "Home_"+i+"_y"
p_df = df[(df["game_id"] == game_id) & (df["player_id"] == i) ]
p_df = df[(df["game_id"] == game_id) & (df["player_id"] ==i) ]
p_df = p_df[['period', 'time','loc_x','loc_y']]

p_df = p_df.rename(columns={
    'time': 'Time [s]',
    'loc_x' : col_x ,
    'loc_y': col_y
})



p_df = p_df.drop_duplicates(subset=["Time [s]"])

final = final.merge(p_df, how='left', on="Time [s]")
final[col_x] = final[col_x +'_y'].fillna(final[col_x+'_x'])
final = final.drop([col_x+'_x', col_x+'_y'], axis=1)
final[col_y] = final[col_y +'_y'].fillna(final[col_y+'_x'])
final = final.drop([col_y+'_x', col_y+'_y'], axis=1)

final

In [ ]:
p_df

In [ ]:
final["Home_87dbfea7-b4c1-49ce-b210-6210f5efae55_y"].unique()

In [ ]:
p_df = p_df.drop_duplicates(subset=["Time [s]"])

final = final.merge(p_df, how='left', left_on=["Time [s]"], right_on=["Time [s]"])

In [ ]:
pd.merge(final,p_df[["Time [s]",col_x,col_y]] ,on='Time [s]' , how='left')

In [ ]:
p_df[p_df["Time [s]"] == 3066.68]

In [ ]:
game_id = 2312135
for tt in range(0,10):
    # tt = 10
    count = tt
    i = player_ids_home[tt]
    print(i)
    col_x = "Home_"+i+"_x"
    col_y = "Home_"+i+"_y"
    p_df = df[(df["game_id"] == game_id) & (df["player_id"] == i) ]
    p_df = df[(df["game_id"] == game_id) & (df["player_id"] ==i) ]
    p_df = p_df[['period', 'time','loc_x','loc_y']]
    if( len(p_df) == 0 ):
        print("cont") # continue
    p_df = p_df.rename(columns={
        'time': 'Time [s]',
        'loc_x' : col_x ,
        'loc_y': col_y
    })
    final = pd.merge(final,p_df ,on='Time [s]' , how='left')
final

In [ ]:
final.to_csv('test.csv')

In [ ]:
final["Time [s]"] = round(final["Time [s]"].astype(float),2)

In [ ]:
df1 = final[final["Time [s]"] == 39.16]
df1

In [ ]:
df2 = df[(df["time"] == 39.16) & (df["game_id"] == game_id) & (df["player_id"] == player_ids_home[10])]
df2

In [ ]:
pd.merge(df1,df2 ,on='Time [s]' , how='left')

In [ ]:
pd.merge(final,p_df ,on='Time [s]' , how='left').to_csv('test.csv')

In [ ]:
p_df["Time [s]"]

In [ ]:

merged_df["time"] = merged_df["time"].astype(float)
p_df["time"] = p_df["time"].astype(float)
# pd.merge(merged_df,p_df , on='time', how='left')
merged_df.merge(p_df.drop_duplicates(subset=['time']), how='left')
merged_df

In [ ]:
p_df["time"]

In [ ]:
merged_df[~merged_df['Home_08d71d20-85ad-4d98-8bc0-36b8e39e517a_x'].isna()]

In [ ]:
df[(df[ 'period' ] ==2) & (df["game_id"] == 2312135)]

In [ ]:
game_id = 2312135
test = df[ (df["player_id"] == player_ids_home[12]) & (df["game_id"] == game_id)] # 10, 12

test.loc[test[ 'period' ] == 2].head(1)
1686694
1686694

In [ ]:
test.tail(1)

In [ ]:
number_of_rows = int(1906.48 / 0.04)


columns = ['Frame', 'Period', 'Time [s]']
data = [list(range(0,number_of_rows+1)) , [1, 1, 1], [0 + (x * 0.04) for x in range(0, number_of_rows+1)]]

df = pd.DataFrame(data, columns=columns)

In [ ]:
df[df["player_id"] == player_ids_home[12] ]["period"].tolist().index(2)
# 712060 - 76667
# 702328 - 76667

In [ ]:
df[df["player_id"] == player_ids_home[10] ]["period"].unique()